### ISSUE TITLE
build_project.sh

### ISSUE THREAD

**Issue by YehudaBialik** [dmikusa/vm_stat_usage_grapher#1]
Do you mind sharing the build_project.sh script that you showed at MacAdmins in 2015?  I finally got around to starting writing some python scripts and I want to start it off properly. Is there a better way to contact you?

**Comment by ghost** [comment]
Here you go:  https://gist.github.com/dmikusa/6e822b27f3f486b9e8fb753de67f9c87

**Comment by YehudaBialik** [comment]
Thanks!  Great presentation by the way.  Although it took me over two years to get back to it, I haven't forgotten your expert advice.
